---
- name: check for short-circuit
  raw: "> /dev/null command -v vim;"
  register: installed
  ignore_errors: True
  changed_when: False

- name: set should_run fact
  set_fact:
    should_run: "{{installed|failed or not vim_should_shortcircuit}}"

- include: include_vars.yml

- include: sudo.yml
  when: ansible_version is not defined or ansible_version.major < 2

- include: become.yml
  when: ansible_version is defined and ansible_version.major >= 2
